import Link from 'next/link'
import Image from 'next/image'
import { notFound } from 'next/navigation'
import { ArrowLeft, ArrowUpRight } from 'lucide-react'
import { MobileCTA, SellerCTA, SectionLabel, SiteFooter, SiteHeader } from '@/components/site'
import { properties } from '@/lib/data'
export function generateStaticParams() { return properties.map((property) => ({ slug: property.slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const property = properties.find((item) => item.slug === slug); return { title: property ? `${property.name} | Maya Bennett` : 'Property | Maya Bennett', description: property?.description } }
export default async function PropertyDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const property = properties.find((item) => item.slug === slug); if (!property) notFound(); return <><SiteHeader /><main className="mx-auto max-w-7xl px-5 py-10 lg:px-10 lg:py-16"><Link href="/properties" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-sage"><ArrowLeft className="size-4" /> Back to properties</Link><div className="mt-10 grid gap-12 lg:grid-cols-[1.2fr_0.8fr] lg:items-center"><div className="relative aspect-[4/3]"><Image src={property.image} alt={property.name} fill priority sizes="(max-width: 1024px) 100vw, 60vw" className="object-cover" /></div><div><SectionLabel>{property.type} · {property.location}</SectionLabel><h1 className="mt-5 font-display text-5xl leading-tight md:text-7xl">{property.name}</h1><p className="mt-5 text-lg">{property.price}</p><p className="mt-2 text-sm text-muted-foreground">{property.details}</p><p className="mt-8 text-base leading-7 text-muted-foreground">{property.description}</p><Link href="/sell" className="button-sage mt-9 w-fit">Discuss your property <ArrowUpRight className="size-4" /></Link></div></div></main><SellerCTA /><SiteFooter /><MobileCTA /></> }
