'use client'

import Link from 'next/link'
import Image from 'next/image'
import { useState } from 'react'
import { ArrowUpRight, Check, ChevronDown, Menu, Moon, Sun, X } from 'lucide-react'
import { properties, faqs } from '@/lib/data'

export function SiteHeader() {
  const [open, setOpen] = useState(false)
  const toggleTheme = () => {
    const next = !document.documentElement.classList.contains('dark')
    document.documentElement.classList.toggle('dark', next)
    try { localStorage.setItem('theme', next ? 'dark' : 'light') } catch {}
  }
  return <header className="border-b border-border/70 bg-background/90 backdrop-blur-md"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-10"><Link href="/" className="font-display text-2xl tracking-wide">Maya Bennett<span className="text-sage">.</span><span className="ml-2 font-sans text-[10px] uppercase tracking-[0.25em] text-muted-foreground">Bennett & Co.</span></Link><nav className="hidden items-center gap-8 text-sm lg:flex"><Link href="/properties" className="nav-link">Properties</Link><Link href="/about" className="nav-link">About</Link><Link href="/#faqs" className="nav-link">FAQs</Link><Link href="/sell" className="button-sage">Sell Your Property <ArrowUpRight className="size-4" /></Link><button onClick={toggleTheme} aria-label="Toggle dark mode" className="rounded-full border border-border p-2 text-muted-foreground hover:text-foreground"><Sun className="hidden size-4 dark:block" /><Moon className="size-4 dark:hidden" /></button></nav><div className="flex items-center gap-2 lg:hidden"><button onClick={toggleTheme} aria-label="Toggle dark mode" className="rounded-full border border-border p-2"><Sun className="hidden size-4 dark:block" /><Moon className="size-4 dark:hidden" /></button><button onClick={() => setOpen(!open)} aria-label={open ? 'Close menu' : 'Open menu'} className="rounded-full border border-border p-2">{open ? <X className="size-5" /> : <Menu className="size-5" />}</button></div></div>{open && <nav className="flex flex-col gap-5 border-t border-border px-5 py-6 lg:hidden"><Link href="/properties" onClick={() => setOpen(false)}>Properties</Link><Link href="/about" onClick={() => setOpen(false)}>About</Link><Link href="/#faqs" onClick={() => setOpen(false)}>FAQs</Link><Link href="/sell" onClick={() => setOpen(false)} className="button-sage w-fit">Sell Your Property <ArrowUpRight className="size-4" /></Link></nav>}</header>
}

export function SiteFooter() { return <footer className="border-t border-border bg-card"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-14 md:grid-cols-3 lg:px-10"><div><Link href="/" className="font-display text-2xl">Maya Bennett<span className="text-sage">.</span></Link><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">A more considered approach to selling Miami property.</p></div><div><p className="eyebrow">Connect</p><div className="mt-4 flex flex-col gap-2 text-sm"><a href="tel:+13055550187" className="hover:text-sage">+1 (305) 555-0187</a><a href="mailto:maya@bennettco.example" className="hover:text-sage">maya@bennettco.example</a></div></div><div><p className="eyebrow">Explore</p><div className="mt-4 flex flex-col gap-2 text-sm"><Link href="/properties">Properties</Link><Link href="/about">About Maya</Link><Link href="/sell">Sell Your Property</Link></div></div></div><div className="mx-auto flex max-w-7xl flex-col gap-2 border-t border-border px-5 py-5 text-xs text-muted-foreground sm:flex-row sm:justify-between lg:px-10"><span>© 2026 Bennett & Co. All rights reserved.</span><span>Privacy · Terms</span></div></footer> }

export function MobileCTA() { return <div className="fixed inset-x-0 bottom-0 z-40 p-3 pb-[calc(0.75rem+env(safe-area-inset-bottom))] lg:hidden"><Link href="/sell" className="button-sage flex w-full justify-center shadow-lg">Sell Your Property <ArrowUpRight className="size-4" /></Link></div> }

export function PropertyCard({ property }: { property: typeof properties[number] }) { return <Link href={`/properties/${property.slug}`} className="group block"><div className="relative aspect-[4/3] overflow-hidden bg-muted"><Image src={property.image} alt={property.name} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105" /></div><div className="flex items-start justify-between gap-4 pt-4"><div><p className="eyebrow">{property.type} · {property.location}</p><h3 className="mt-2 font-display text-2xl">{property.name}</h3></div><ArrowUpRight className="mt-1 size-5 text-muted-foreground transition group-hover:text-sage" /></div><p className="mt-2 text-sm text-muted-foreground">{property.details} · {property.price}</p></Link> }

export function PropertyGrid({ limit }: { limit?: number }) { return <div className="grid gap-10 md:grid-cols-3">{properties.slice(0, limit).map((p) => <PropertyCard key={p.slug} property={p} />)}</div> }

export function FAQ() { const [active, setActive] = useState<number | null>(null); return <div className="divide-y divide-border border-y border-border">{faqs.map((faq, i) => <div key={faq.q}><button className="flex w-full items-center justify-between gap-5 py-5 text-left" aria-expanded={active === i} onClick={() => setActive(active === i ? null : i)}><span className="font-display text-xl">{faq.q}</span><ChevronDown className={`size-5 shrink-0 transition ${active === i ? 'rotate-180 text-sage' : ''}`} /></button>{active === i && <p className="max-w-2xl pb-5 text-sm leading-7 text-muted-foreground">{faq.a}</p>}</div>)}</div> }

export function SellerForm() { const [step, setStep] = useState(0); const [done, setDone] = useState(false); const [values, setValues] = useState<Record<string,string>>({}); const steps = [{ key: 'address', label: 'Where is the property?', placeholder: 'Property address', type: 'text' }, { key: 'type', label: 'What kind of property is it?', placeholder: 'e.g. Single-family home', type: 'text' }, { key: 'value', label: 'What is its approximate value?', placeholder: 'e.g. $2.5M', type: 'text' }, { key: 'timeline', label: 'What is your ideal timeline?', placeholder: 'e.g. Exploring the next 6–12 months', type: 'text' }, { key: 'name', label: 'How can Maya reach you?', placeholder: 'Your name', type: 'text' }]; const current = steps[step]; const update = (v: string) => setValues({ ...values, [current.key]: v }); const next = () => { if (!values[current.key]?.trim()) return; if (step === steps.length - 1) setDone(true); else setStep(step + 1) }; if (done) return <div className="border border-border bg-card p-8 text-center md:p-14"><div className="mx-auto flex size-12 items-center justify-center rounded-full bg-sage text-sage-foreground"><Check className="size-5" /></div><h2 className="mt-6 font-display text-4xl">Thank you. Maya will be in touch shortly.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-7 text-muted-foreground">Your information stays private. This prototype does not submit or store your details.</p></div>; return <div className="border border-border bg-card p-6 md:p-10"><div className="mb-10 flex items-center justify-between text-xs text-muted-foreground"><span>Step {step + 1} of {steps.length}</span><span>{Math.round(((step + 1) / steps.length) * 100)}%</span></div><div className="mb-2 h-1 bg-muted"><div className="h-1 bg-sage transition-all" style={{ width: `${((step + 1) / steps.length) * 100}%` }} /></div><label htmlFor={current.key} className="mt-10 block font-display text-3xl md:text-4xl">{current.label}</label><input id={current.key} autoFocus value={values[current.key] || ''} onChange={(e) => update(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.nativeEvent.isComposing && e.keyCode !== 229) next() }} placeholder={current.placeholder} className="mt-6 w-full border-b border-border bg-transparent py-4 text-lg outline-none placeholder:text-muted-foreground/60 focus:border-sage" aria-required="true" /><div className="mt-10 flex justify-between"><button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} className="text-sm text-muted-foreground disabled:opacity-30">Back</button><button onClick={next} className="button-sage">{step === steps.length - 1 ? 'Finish' : 'Continue'} <ArrowUpRight className="size-4" /></button></div></div> }

export function SellerCTA() { return <section className="bg-sage text-sage-foreground"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-16 md:flex-row md:items-end md:justify-between lg:px-10"><div><p className="eyebrow text-sage-foreground/70">A first conversation</p><h2 className="mt-4 max-w-xl font-display text-4xl leading-tight md:text-6xl">Your next move deserves a clear point of view.</h2></div><Link href="/sell" className="button-light w-fit">Sell Your Property <ArrowUpRight className="size-4" /></Link></div></section> }

export function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="eyebrow text-sage">{children}</p> }
export function IntroImage({ src, alt, className = '' }: { src: string; alt: string; className?: string }) { return <div className={`relative overflow-hidden ${className}`}><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div> }

export { ArrowUpRight }
